### PR TITLE
button-up

### PR DESCRIPTION
**Pull request by krimuwka**

### CODE REVIEW

**Review by m0h4x — APPROVED** [review]
if i look at the files that are being added here. Like a html, js, scss and an svg. Plus a line in the main index. It all looks to me very reasonable. Honestly i havent figured out yet a way to test it locally on my machine right now so i could see if it really actually would break anything. So im going to just approve it. Hoping the mighty team lead then can test it and merge eventually. Would be very appreciated. :)

**Comment by m0h4x** [comment]
or maybe who knows wouldnt it hurt to really merge it and pray that it works. :)

**Comment by PavloLevchenko** [comment]
don't do that again 🚨 /home/runner/work/Filmoteka/Filmoteka/src/index.html: ENOENT: no such file or directory, open '/home/runner/work/Filmoteka/Filmoteka/src/partials/button-up .html'
    at Object.openSync(node:fs:585:3)
    at Object.readFileSync(node:fs:453:35)
    at /home/runner/work/Filmoteka/Filmoteka/node_modules/posthtml-include/lib/index.js:31:21
    at /home/runner/work/Filmoteka/Filmoteka/node_modules/posthtml/lib/api.js:91:45
    at traverse (/home/runner/work/Filmoteka/Filmoteka/node_modules/posthtml/lib/api.js:105:26)
    at traverse (/home/runner/work/Filmoteka/Filmoteka/node_modules/posthtml/lib/api.js:111:5)
    at traverse (/home/runner/work/Filmoteka/Filmoteka/node_modules/posthtml/lib/api.js:105:17)
    at traverse (/home/runner/work/Filmoteka/Filmoteka/node_modules/posthtml/lib/api.js:111:5)
    at traverse (/home/runner/work/Filmoteka/Filmoteka/node_modules/posthtml/lib/api.js:105:17)
    at Array.match(/home/runner/work/Filmoteka/Filmoteka/node_modules/posthtml/lib/api.js:90:7)
Error: Process completed with exit code 1.

**Comment by m0h4x** [comment]
ouch, let some noobs contribute to your project :D (i mean like me, breaking stuff, peoples work) :D

**Pull request merged**
